export { default as Navbar } from './Navbar';
export { default as Hero } from './Hero';
export { default as About } from './About';
export { default as Skills } from './Skills';
export { default as Education } from './Education';
export { default as Projects } from './Projects';
export { default as Leadership } from './Leadership';
export { default as Interests } from './Interests';
export { default as Contact } from './Contact';
